dist: trusty
sudo: false

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js
node_js:
  - "10.4.1"

branches:
  only:
    - master

cache:
  directories:
    - ./node_modules

before_script:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli

script:
  - npm install codecov -g
  - ng lint
  - ng build --prod --aot
  - ng test --watch=false

after_success:
  - codecov